// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRhNGfo246HVS7ClidlBVOdKKlvnK65I',
    appId: '1:295896292996:web:efae6a82a327aed2e7acd1',
    messagingSenderId: '295896292996',
    projectId: 'chatiar-app',
    authDomain: 'chatiar-app.firebaseapp.com',
    storageBucket: 'chatiar-app.firebasestorage.app',
    measurementId: 'G-VCDE7S38YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapZtlIc7s8CNZkqTz4mYIgT2lYXfq6Oo',
    appId: '1:295896292996:android:7f0e5de3f8f463ece7acd1',
    messagingSenderId: '295896292996',
    projectId: 'chatiar-app',
    storageBucket: 'chatiar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukfR435B8YXkHwAnMDmJnwDGHNQsldXk',
    appId: '1:295896292996:ios:2ab39e2a8d423375e7acd1',
    messagingSenderId: '295896292996',
    projectId: 'chatiar-app',
    storageBucket: 'chatiar-app.firebasestorage.app',
    androidClientId: '295896292996-4bgpokvruk9cph49g62goapn1ppe46dt.apps.googleusercontent.com',
    iosClientId: '295896292996-dplesbu7qfcsqeo5m0aij6lhvifecmsr.apps.googleusercontent.com',
    iosBundleId: 'com.esceptechos.chatiarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukfR435B8YXkHwAnMDmJnwDGHNQsldXk',
    appId: '1:295896292996:ios:2ab39e2a8d423375e7acd1',
    messagingSenderId: '295896292996',
    projectId: 'chatiar-app',
    storageBucket: 'chatiar-app.firebasestorage.app',
    androidClientId: '295896292996-4bgpokvruk9cph49g62goapn1ppe46dt.apps.googleusercontent.com',
    iosClientId: '295896292996-dplesbu7qfcsqeo5m0aij6lhvifecmsr.apps.googleusercontent.com',
    iosBundleId: 'com.esceptechos.chatiarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlRhNGfo246HVS7ClidlBVOdKKlvnK65I',
    appId: '1:295896292996:web:e23a5d80302d7e12e7acd1',
    messagingSenderId: '295896292996',
    projectId: 'chatiar-app',
    authDomain: 'chatiar-app.firebaseapp.com',
    storageBucket: 'chatiar-app.firebasestorage.app',
    measurementId: 'G-EFWX0365QY',
  );
}
